# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('comment', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='bug', max_length=10)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('date_accepted', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
