# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20181123_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_accepted',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='date_completed',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='date_started',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=6),
        ),
    ]
