# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20181123_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
