# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20181130_1640'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='komment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='commentary',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='comments',
            name='issue',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text_length',
            field=models.CharField(default='', max_length=254),
        ),
    ]
